version: '3.8'

services:
  fiap_api_alunos:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # Ou Production, dependendo do ambiente